### ISSUE TITLE
Control over structure of reservoir

### ISSUE THREAD

**Issue by fps** [peakbook/EchoStateNetworks.jl#1]
Hi,

I'm planning to do some experiments where I alter the connectivity structure of the reservoir (basically I'll sample the adjacency matrix from some distribution) and wonder how to incorporate this into this package?

The only control at the time being seems to be the sparsity argument.

Maybe a second EchoStateNetwork "constructor" (sorry for the c++ talk) which also takes an adjacency matrix as an argument?

**Comment by peakbook** [comment]
The weight matrices Wi, Wr, and Wf are initialized in [init_weight!](https://github.com/peakbook/EchoStateNetworks.jl/blob/6a8c3a7c64fd60a213124bf4e1d2fc405840534a/src/EchoStateNetworks.jl#L59). So, if you want alter these matrices, change the function definition.

You can also access and alter these weight matrices from member variable of EchoStateNetwork object because it is defined as mutable struct.

**Comment by fps** [comment]
Hi! Thanks for your quick reply. I guess altering them post-construction via the member variables is the least intrusive way then. :)
